name: Test Panna Monitor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          playwright install chromium

      - name: Run Monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check.py

      - name: Upload Screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: browser-screenshot
          path: full_vehicle.png

      - name: Commit Updated State
        run: |
          if git diff --quiet state.json; then
            echo "No state change."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add state.json
            git commit -m "Update monitor state [skip ci]"
            git push
          fi
